---
- name: Say Hello using Custom Module
  hosts: localhost
  connection: local
  gather_facts: false

  vars_prompt:
    - name: "user_input"
      prompt: "Enter your name"
      private: no

  tasks:
    - name: Run custom hello_user module
      hello_user:
        name: "{{ user_input }}"
